-- Generated by generate_demo_seed.mjs — do not edit by hand.
-- Rich demo catalog: upserts by SKU (idempotent), images stay untouched so
-- real photos added later via the admin UI are never overwritten.

-- פרזול › ידיות ריהוט
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('ידית אלומיניום שחורה 128mm', 'HD-128-BLK', 'פרזול', 'ידיות ריהוט', 'ידית פרופיל אלומיניום בגימור שחור מט, מרחק קדיחה 128 מ"מ. קו נקי למטבחים וארונות מודרניים, כולל ברגי חיבור.', 38, true, null, true, '[]'::jsonb),
  ('ידית פליז עתיק 96mm', 'HD-096-BRS', 'פרזול', 'ידיות ריהוט', 'ידית קשת בגימור פליז עתיק, מרחק קדיחה 96 מ"מ. מתאימה לריהוט כפרי וקלאסי, ציפוי עמיד בשחיקה.', 45, true, null, true, '[]'::jsonb),
  ('ידית פרופיל סקנדי', 'HD-SCAN', 'פרזול', 'ידיות ריהוט', 'ידית פרופיל בקו סקנדינבי נקי, אלומיניום מאולגן בגימור טבעי. נמכרת ליחידה כולל ברגים, מגוון מרחקי קדיחה.', 32, true, 'מבצע', false, '[{"label":"128mm","sku":"HD-SCAN-128"},{"label":"160mm","sku":"HD-SCAN-160"},{"label":"192mm","sku":"HD-SCAN-192"},{"label":"256mm","sku":"HD-SCAN-256"}]'::jsonb),
  ('ידית קשת ברצלונה', 'HD-BARC', 'פרזול', 'ידיות ריהוט', 'ידית קשת מעוגלת מסגסוגת אבץ ביציקת דיוק, מרחק קדיחה 160 מ"מ. מגע נעים ומשקל איכותי, בשלושה גימורים.', 42, true, null, false, '[{"label":"שחור מט","sku":"HD-BARC-BLK"},{"label":"ניקל מוברש","sku":"HD-BARC-NKL"},{"label":"פליז מוברש","sku":"HD-BARC-BRS"}]'::jsonb),
  ('כפתור אוסלו', 'HD-OSLO', 'פרזול', 'ידיות ריהוט', 'כפתור עגול קוטר 30 מ"מ למגירות וארונות. בסיס פליז מלא, מתאים גם לשימוש אינטנסיבי.', 18, true, 'חדש', false, '[{"label":"שחור מט","sku":"HD-OSLO-BLK"},{"label":"ניקל מוברש","sku":"HD-OSLO-NKL"},{"label":"פליז מוברש","sku":"HD-OSLO-BRS"},{"label":"לבן מט","sku":"HD-OSLO-WHT"}]'::jsonb),
  ('ידית אינטגרלית מילאנו', 'HD-MILA', 'פרזול', 'ידיות ריהוט', 'פרופיל ידית אינטגרלית שקועה (Gola) להתקנה בקנט העליון של החזית. אלומיניום מאולגן, חיתוך למידה.', 56, true, null, false, '[{"label":"200mm","sku":"HD-MILA-200"},{"label":"350mm","sku":"HD-MILA-350"},{"label":"600mm","sku":"HD-MILA-600"}]'::jsonb),
  ('ידית גומחה טוקיו', 'HD-TOKY', 'פרזול', 'ידיות ריהוט', 'ידית גומחה שקועה מלבנית 140 מ"מ לדלתות הזזה וריהוט מינימליסטי. התקנה בכרסום, ללא בליטות.', 36, true, null, false, '[{"label":"שחור מט","sku":"HD-TOKY-BLK"},{"label":"נירוסטה","sku":"HD-TOKY-INX"}]'::jsonb),
  ('ידית צדף כפרית', 'HD-RUST', 'פרזול', 'ידיות ריהוט', 'ידית צדף בסגנון כפרי ליציקת מגירות מטבח, רוחב 96 מ"מ. גימור עתיק מוברש בעבודת יד.', 28, true, null, false, '[{"label":"ברונזה עתיקה","sku":"HD-RUST-BRZ"},{"label":"פליז מוברש","sku":"HD-RUST-BRS"}]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- פרזול › צירים ומנגנונים
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('ציר סמוי 110° Soft-Close', 'HG-SOFT-35', 'פרזול', 'צירים ומנגנונים', 'ציר כוס 35 מ"מ עם בולם טריקה מובנה, פתיחה 110°. כיוונון תלת-מימדי, קליפס שחרור מהיר. נמכר ליחידה.', 12, true, null, true, '[{"label":"ישר","sku":"HG-SOFT-35-S"},{"label":"חצי כפוף","sku":"HG-SOFT-35-H"},{"label":"כפוף","sku":"HG-SOFT-35-F"}]'::jsonb),
  ('ציר פינה 165°', 'HG-CORN-165', 'פרזול', 'צירים ומנגנונים', 'ציר פתיחה רחבה 165° לארונות פינה ופתרונות סלייד. כוס 35 מ"מ, כולל פלטת הרכבה.', 24, true, null, false, '[]'::jsonb),
  ('ציר לדלת זכוכית', 'HG-GLAS', 'פרזול', 'צירים ומנגנונים', 'ציר ייעודי לדלתות זכוכית 4–6 מ"מ ללא קדיחה בזכוכית. כולל עיגון ותפס דקורטיבי.', 29, true, 'מבצע', false, '[{"label":"ניקל מוברש","sku":"HG-GLAS-NKL"},{"label":"שחור מט","sku":"HG-GLAS-BLK"}]'::jsonb),
  ('בולם טריקה חיצוני', 'HG-DAMP', 'פרזול', 'צירים ומנגנונים', 'בולם טריקה הידראולי להוספה על צירים קיימים. התקנת לחיצה מהירה, האטה שקטה ואחידה.', 6, true, null, false, '[]'::jsonb),
  ('מנגנון הרמה אנכי אוונטו', 'HG-AVNT', 'פרזול', 'צירים ומנגנונים', 'מנגנון קלפה להרמת חזית כלפי מעלה עם עצירה בכל נקודה. כיול כוח לפי משקל הדלת, כולל תבנית קדיחה.', 165, true, null, false, '[{"label":"דלת קטנה","sku":"HG-AVNT-S"},{"label":"דלת בינונית","sku":"HG-AVNT-M"},{"label":"דלת גדולה","sku":"HG-AVNT-L"}]'::jsonb),
  ('מנגנון Push-Open מגנטי', 'HG-PUSH', 'פרזול', 'צירים ומנגנונים', 'מנגנון פתיחה בלחיצה לדלתות ללא ידית. ראש מגנטי מתכוונן, התקנה בקדח 10 מ"מ או במתלה.', 9, true, 'חדש', false, '[]'::jsonb),
  ('ציר פסנתר 2 מטר', 'HG-PIAN-2M', 'פרזול', 'צירים ומנגנונים', 'ציר רציף באורך 2 מטר, ניתן לחיתוך. עובי כנף 1.2 מ"מ, קדחים שקועים מוכנים.', 34, true, null, false, '[{"label":"נירוסטה","sku":"HG-PIAN-2M-INX"},{"label":"פליז מוברש","sku":"HG-PIAN-2M-BRS"}]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- פרזול › מסילות ומגירות
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('מסילה טלסקופית מיסבים', 'RL-TELE', 'פרזול', 'מסילות ומגירות', 'זוג מסילות טלסקופיות שליפה מלאה על מיסבים כדוריים, עומס עד 35 ק"ג. פירוק מהיר בלשונית.', 22, true, null, true, '[{"label":"250mm","sku":"RL-TELE-250"},{"label":"350mm","sku":"RL-TELE-350"},{"label":"450mm","sku":"RL-TELE-450"},{"label":"550mm","sku":"RL-TELE-550"}]'::jsonb),
  ('מסילת סמויה Soft-Close', 'RL-UNDER', 'פרזול', 'מסילות ומגירות', 'זוג מסילות תחתית סמויות עם סגירה רכה ושליפה מלאה. כיוונון גובה וצד, עומס 30 ק"ג.', 48, true, null, false, '[{"label":"300mm","sku":"RL-UNDER-300"},{"label":"400mm","sku":"RL-UNDER-400"},{"label":"500mm","sku":"RL-UNDER-500"}]'::jsonb),
  ('מערכת מגירה דקה', 'RL-SLIM', 'פרזול', 'מסילות ומגירות', 'מערכת דפנות מגירה ממתכת בעובי 13 מ"מ עם מסילות סמויות וסגירה רכה. מראה נקי, הרכבה מהירה.', 95, true, null, false, '[{"label":"נמוכה 84","sku":"RL-SLIM-84"},{"label":"בינונית 118","sku":"RL-SLIM-118"},{"label":"גבוהה 185","sku":"RL-SLIM-185"}]'::jsonb),
  ('מסילה כבדה 45 ק"ג', 'RL-HVY-45', 'פרזול', 'מסילות ומגירות', 'מסילה טלסקופית מחוזקת לעומסים כבדים — מגירות כלים, מזווה ומשטחי עבודה נשלפים.', 64, true, 'מבצע', false, '[{"label":"450mm","sku":"RL-HVY-45-450"},{"label":"600mm","sku":"RL-HVY-45-600"},{"label":"750mm","sku":"RL-HVY-45-750"}]'::jsonb),
  ('ערכת גלגלות לדלת הזזה', 'RL-SLID', 'פרזול', 'מסילות ומגירות', 'ערכה לדלת הזזה תלויה עד 60 ק"ג: זוג גלגלות מיסב, מסילת אלומיניום 2 מ'' ומגבילים.', 78, true, null, false, '[]'::jsonb),
  ('סל נשלף למזווה', 'RL-PULL', 'פרזול', 'מסילות ומגירות', 'סל רשת כרום נשלף עם מסילות Soft-Close לארון מזווה 30 ס"מ. כולל תפסי חיבור לחזית.', 230, true, 'חדש', false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- פרזול › פרזול בניין
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('ידית בניין ריגה', 'BH-RIGA', 'פרזול', 'פרזול בניין', 'ידית מנוף על רוזטה לדלתות פנים, קפיץ החזרה מובנה. עמידות 200,000 מחזורי פתיחה.', 89, true, null, false, '[{"label":"שחור מט","sku":"BH-RIGA-BLK"},{"label":"ניקל מוברש","sku":"BH-RIGA-NKL"},{"label":"ברונזה עתיקה","sku":"BH-RIGA-BRZ"}]'::jsonb),
  ('צילינדר 5 מפתחות', 'BH-CYL', 'פרזול', 'פרזול בניין', 'צילינדר פיני 5 מפתחות ניקל עם כרטיס שכפול. הגנת קידוח, תקן ישראלי.', 95, true, 'חדש', true, '[{"label":"60mm","sku":"BH-CYL-60"},{"label":"70mm","sku":"BH-CYL-70"},{"label":"80mm","sku":"BH-CYL-80"},{"label":"90mm","sku":"BH-CYL-90"}]'::jsonb),
  ('מנעול חבוי מגנטי', 'BH-HLOCK', 'פרזול', 'פרזול בניין', 'מנעול חבוי עם לשונית מגנטית שקטה לדלתות פנים. נעילה חלקה ללא רעש טריקה.', 42, true, null, false, '[]'::jsonb),
  ('מעצור דלת מגנטי', 'BH-STOP', 'פרזול', 'פרזול בניין', 'מעצור רצפה עם תפיסה מגנטית. בסיס נירוסטה מוברגת, גומי בולם פגיעות.', 19, true, null, false, '[{"label":"שחור מט","sku":"BH-STOP-BLK"},{"label":"נירוסטה","sku":"BH-STOP-INX"},{"label":"לבן מט","sku":"BH-STOP-WHT"}]'::jsonb),
  ('קולב קיר כפול', 'BH-HOOK', 'פרזול', 'פרזול בניין', 'קולב כפול ממתכת ביציקה לדלתות וקירות. עומס עד 10 ק"ג, ברגים והרחבות כלולים.', 14, true, null, false, '[{"label":"שחור מט","sku":"BH-HOOK-BLK"},{"label":"ניקל מוברש","sku":"BH-HOOK-NKL"},{"label":"פליז מוברש","sku":"BH-HOOK-BRS"}]'::jsonb),
  ('רוזטה לצילינדר', 'BH-ROSE', 'פרזול', 'פרזול בניין', 'רוזטת מגן עגולה לצילינדר, התקנה נסתרת. מתאימה לדלתות פנים וכניסה.', 11, true, 'מבצע', false, '[{"label":"שחור מט","sku":"BH-ROSE-BLK"},{"label":"ניקל מוברש","sku":"BH-ROSE-NKL"}]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- פרזול › אביזרי אמבט
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('מתלה מגבת 60 ס"מ', 'BA-TOWL-60', 'פרזול', 'אביזרי אמבט', 'מוט מגבת 60 ס"מ מנירוסטה 304 בציפוי PVD עמיד אדים. התקנה בהברגה סמויה.', 65, true, null, false, '[{"label":"שחור מט","sku":"BA-TOWL-60-BLK"},{"label":"כרום מבריק","sku":"BA-TOWL-60-CRM"},{"label":"פליז מוברש","sku":"BA-TOWL-60-BRS"}]'::jsonb),
  ('וו תלייה לאמבט', 'BA-HOOK', 'פרזול', 'אביזרי אמבט', 'וו בודד מעוגל לחדר רחצה, נירוסטה מלאה. הדבקה תעשייתית או הברגה — שתי האפשרויות בערכה.', 16, true, null, false, '[{"label":"שחור מט","sku":"BA-HOOK-BLK"},{"label":"כרום מבריק","sku":"BA-HOOK-CRM"}]'::jsonb),
  ('מדף זכוכית 50 ס"מ', 'BA-SHLF', 'פרזול', 'אביזרי אמבט', 'מדף זכוכית מחוסמת 8 מ"מ עם תפסי נירוסטה ומעקה עדין. נושא עד 5 ק"ג.', 88, true, null, true, '[]'::jsonb),
  ('מחזיק נייר עם מדף', 'BA-PAPR', 'פרזול', 'אביזרי אמבט', 'מחזיק נייר טואלט עם מדף עליון לטלפון. יציקת אבץ בציפוי עמיד לחות.', 49, true, null, false, '[{"label":"שחור מט","sku":"BA-PAPR-BLK"},{"label":"כרום מבריק","sku":"BA-PAPR-CRM"}]'::jsonb),
  ('ידית אחיזה בטיחותית', 'BA-GRAB', 'פרזול', 'אביזרי אמבט', 'מאחז בטיחות נירוסטה 32 מ"מ בתקן נגישות, עיגון 3 נקודות. עומס מבחן 150 ק"ג.', 72, true, 'חדש', false, '[{"label":"300mm","sku":"BA-GRAB-300"},{"label":"450mm","sku":"BA-GRAB-450"},{"label":"600mm","sku":"BA-GRAB-600"}]'::jsonb),
  ('מראה עגולה עם תאורת LED', 'BA-MIRR-LED', 'פרזול', 'אביזרי אמבט', 'מראה קוטר 60 ס"מ עם טבעת LED היקפית ומתג מגע. דרגות תאורה ואדים-נטרול מובנה.', 320, true, 'חדש', true, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- חומרי גלם › לוחות ופלטות
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('לוח MDF גולמי', 'RW-MDF-18', 'חומרי גלם', 'לוחות ופלטות', 'לוח MDF גולמי 122/244 ס"מ בצפיפות תעשייתית אחידה, מתאים לצביעה ולציפוי. המחיר לגיליון בעובי 18 מ"מ.', 135, true, null, true, '[{"label":"6mm","sku":"RW-MDF-6"},{"label":"12mm","sku":"RW-MDF-12"},{"label":"18mm","sku":"RW-MDF-18"},{"label":"30mm","sku":"RW-MDF-30"}]'::jsonb),
  ('פלטת סנדוויץ'' מצופה לבן', 'RW-MEL-16', 'חומרי גלם', 'לוחות ופלטות', 'פלטת לבידים מצופה מלמין לבן דו-צדדי 122/244 ס"מ. ליבה יציבה במשקל נמוך, חיתוך נקי.', 98, true, 'מבצע', false, '[{"label":"12mm","sku":"RW-MEL-12"},{"label":"16mm","sku":"RW-MEL-16"},{"label":"22mm","sku":"RW-MEL-22"}]'::jsonb),
  ('לוח מלמין מגוון', 'RW-MELC', 'חומרי גלם', 'לוחות ופלטות', 'לוח שבבית מצופה מלמין דקורטיבי 18 מ"מ בגווני פרימיום תואמי קנט. גיליון 122/244 ס"מ.', 145, true, null, false, '[{"label":"אלון טבעי","sku":"RW-MELC-OAK"},{"label":"אגוז","sku":"RW-MELC-WAL"},{"label":"אפור בטון","sku":"RW-MELC-GRY"},{"label":"לבן משי","sku":"RW-MELC-WHT"}]'::jsonb),
  ('דיקט ליבנה פיני', 'RW-PLY-BIR', 'חומרי גלם', 'לוחות ופלטות', 'לבידי ליבנה BB/BB בהדבקה עמידת מים, שכבות מלאות ללא חללים. מתאים לרהיטים בחשיפת קנט.', 260, true, null, true, '[{"label":"9mm","sku":"RW-PLY-BIR-9"},{"label":"12mm","sku":"RW-PLY-BIR-12"},{"label":"18mm","sku":"RW-PLY-BIR-18"}]'::jsonb),
  ('לוח OSB-3', 'RW-OSB-11', 'חומרי גלם', 'לוחות ופלטות', 'לוח OSB-3 בעובי 11 מ"מ לקונסטרוקציה ועבודות מבנה, עמיד לחות. גיליון 122/244 ס"מ.', 72, true, null, false, '[]'::jsonb),
  ('לוח MDF ירוק עמיד לחות', 'RW-MDF-MR', 'חומרי גלם', 'לוחות ופלטות', 'לוח MDF בדרגת עמידות לחות MR לסביבת מטבח ואמבט. ליבה ירוקה מזוהה, גיליון 122/244 ס"מ.', 168, true, null, false, '[{"label":"12mm","sku":"RW-MDF-MR-12"},{"label":"18mm","sku":"RW-MDF-MR-18"}]'::jsonb),
  ('פורמייקה HPL', 'RW-HPL', 'חומרי גלם', 'לוחות ופלטות', 'למינט בלחץ גבוה 0.8 מ"מ להדבקה על פלטה, עמיד שריטות וחום. גיליון 130/305 ס"מ.', 190, true, null, false, '[{"label":"לבן מט","sku":"RW-HPL-WHT"},{"label":"שחור סופר-מט","sku":"RW-HPL-BLK"},{"label":"שיש קררה","sku":"RW-HPL-MRB"}]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- חומרי גלם › פורניר וקצוות
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('פורניר אלון טבעי', 'RW-VEN-OAK', 'חומרי גלם', 'פורניר וקצוות', 'גיליון פורניר אלון פרוס 0.6 מ"מ על פלייס, רוחב 64 ס"מ. גוון בהיר אחיד וטקסטורה ישרה.', 95, true, 'חדש', false, '[]'::jsonb),
  ('פורניר אגוז אמריקאי', 'RW-VEN-WAL', 'חומרי גלם', 'פורניר וקצוות', 'פורניר אגוז אמריקאי בגוון עמוק עם עורקים טבעיים. גיליון 250/64 ס"מ, 0.6 מ"מ.', 140, true, 'מבצע', false, '[]'::jsonb),
  ('פורניר מייפל', 'RW-VEN-MPL', 'חומרי גלם', 'פורניר וקצוות', 'פורניר מייפל קנדי בהיר וחלק במיוחד, אידיאלי לגימור שקוף. גיליון 250/64 ס"מ.', 105, true, 'מבצע', false, '[]'::jsonb),
  ('סרט קצה ABS', 'RW-EDGE-ABS', 'חומרי גלם', 'פורניר וקצוות', 'סרט קנט ABS בעובי 1 מ"מ עם תחתית פריימר להדבקה תעשייתית. המחיר למטר רץ.', 3, true, null, true, '[{"label":"22mm לבן","sku":"RW-EDGE-ABS-22W"},{"label":"22mm אלון","sku":"RW-EDGE-ABS-22O"},{"label":"45mm לבן","sku":"RW-EDGE-ABS-45W"},{"label":"45mm אגוז","sku":"RW-EDGE-ABS-45N"}]'::jsonb),
  ('סרט קצה מלמין עם דבק', 'RW-EDGE-MEL', 'חומרי גלם', 'פורניר וקצוות', 'קנט מלמין 22 מ"מ עם דבק חם מובנה להדבקה במגהץ ביתי. גליל 10 מטר, גוון לבן.', 2, true, null, false, '[]'::jsonb),
  ('סרט הדבקת פורניר', 'RW-VEN-TAPE', 'חומרי גלם', 'פורניר וקצוות', 'נייר דבק מחורר לחיבור גיליונות פורניר לפני כבישה. גליל 200 מטר ברוחב 20 מ"מ.', 28, true, null, false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- חומרי גלם › עץ מלא
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('קורת אלון מהוקצעת', 'RW-OAK-BEAM', 'חומרי גלם', 'עץ מלא', 'אלון אירופאי מיובש תנור 8% לחות, מהוקצע 4 צדדים. מחיר ליחידה באורך 240 ס"מ.', 220, true, null, false, '[{"label":"20/45/2400","sku":"RW-OAK-BEAM-2045"},{"label":"45/45/2400","sku":"RW-OAK-BEAM-4545"},{"label":"20/90/2400","sku":"RW-OAK-BEAM-2090"}]'::jsonb),
  ('לוח אורן מהוקצע', 'RW-PINE-PLN', 'חומרי גלם', 'עץ מלא', 'אורן פיני נקי מסיקוסים גדולים, מהוקצע ומלוטש. אורך 240 ס"מ, מתאים לרהיטים ומדפים.', 45, true, null, false, '[{"label":"19/90/2400","sku":"RW-PINE-PLN-1990"},{"label":"19/140/2400","sku":"RW-PINE-PLN-19140"},{"label":"28/140/2400","sku":"RW-PINE-PLN-28140"}]'::jsonb),
  ('פלטת אגוז אמריקאי', 'RW-WAL-SLAB', 'חומרי גלם', 'עץ מלא', 'פלטת אגוז אמריקאי מלא 26/200/1200 מ"מ, מיובש תנור ומיושר. לשולחנות ומשטחים ייחודיים.', 850, true, null, true, '[]'::jsonb),
  ('לוח אשור מבוקע', 'RW-BEECH-PLN', 'חומרי גלם', 'עץ מלא', 'אשור אירופאי מאודה 25/120/2000 מ"מ, סיב צפוף ואחיד. מצוין לחיתוכי CNC ולמדרגות.', 120, true, 'חדש', false, '[]'::jsonb),
  ('דבקית אלון', 'RW-OAK-PANEL', 'חומרי גלם', 'עץ מלא', 'פאנל אלון מודבק בלוחות רציפים (דבקית), מלוטש P120 ומוכן לגימור. לחזיתות ומשטחי עבודה.', 380, true, 'מבצע', true, '[{"label":"18/600/2400","sku":"RW-OAK-PANEL-18600"},{"label":"26/600/2400","sku":"RW-OAK-PANEL-26600"}]'::jsonb),
  ('לוח טיק לחוץ', 'RW-TEAK-PLN', 'חומרי גלם', 'עץ מלא', 'טיק אמיתי 19/90/1800 מ"מ עמיד מזג אוויר באופן טבעי. לריהוט גן, סיפונים ואדניות.', 290, true, 'חדש', false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- דבקים › דבק לעץ
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('דבק נגרים Titebond II', 'GL-TB2-946', 'דבקים', 'דבק לעץ', 'דבק נגרים עמיד מים (D3) בייבוש מהיר, קו הדבקה שקוף-ענברי. המוביל בסדנאות נגרות.', 62, true, null, true, '[{"label":"237mL","sku":"GL-TB2-237"},{"label":"473mL","sku":"GL-TB2-473"},{"label":"946mL","sku":"GL-TB2-946"},{"label":"3.8L","sku":"GL-TB2-3800"}]'::jsonb),
  ('דבק נגרים Titebond III', 'GL-TB3', 'דבקים', 'דבק לעץ', 'הדור העמיד ביותר (D4) — חיבורי חוץ ומשטחי מגע מזון. זמן עבודה ארוך, חוזק קו גבוה מהעץ.', 78, true, null, false, '[{"label":"473mL","sku":"GL-TB3-473"},{"label":"946mL","sku":"GL-TB3-946"},{"label":"3.8L","sku":"GL-TB3-3800"}]'::jsonb),
  ('דבק נגרים Titebond Original', 'GL-TBO', 'דבקים', 'דבק לעץ', 'הקלאסי לפנים הבית: אחיזה ראשונית חזקה, נשייף ללא מריחה. אידיאלי לרהיטים ועבודות פנים.', 48, true, null, false, '[{"label":"473mL","sku":"GL-TBO-473"},{"label":"946mL","sku":"GL-TBO-946"}]'::jsonb),
  ('דבק PVA מהיר', 'GL-PVA-FAST', 'דבקים', 'דבק לעץ', 'דבק לבן שקוף-ייבוש עם אחיזה תוך 10 דקות. לעבודות הרכבה סדרתיות ולחיזוק פינות.', 32, true, null, false, '[{"label":"500mL","sku":"GL-PVA-FAST-500"},{"label":"1L","sku":"GL-PVA-FAST-1000"},{"label":"5L","sku":"GL-PVA-FAST-5000"}]'::jsonb),
  ('אקדח דבק חם מקצועי', 'GL-HOT-GUN', 'דבקים', 'דבק לעץ', 'אקדח דבק 100W עם ויסות טמפרטורה וזרימה. קצה פליז מתחלף, מתאים למקלות 11 מ"מ.', 145, true, null, false, '[]'::jsonb),
  ('מקלות דבק חם (1 ק"ג)', 'GL-HOT-STK', 'דבקים', 'דבק לעץ', 'מקלות דבק חם שקופים 11/200 מ"מ באריזת קילו. נקודת התכה 193°, אחיזה חזקה לעץ ובד.', 38, true, null, true, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- דבקים › דבק מגע ואפוקסי
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('דבק מגע נוזלי', 'GL-CON-1L', 'דבקים', 'דבק מגע ואפוקסי', 'דבק מגע ניאופרן למריחה דו-צדדית — פורמייקה, גומי ועור. זמן פתוח 15 דקות, אחיזה מיידית.', 48, true, 'מבצע', false, '[{"label":"1L","sku":"GL-CON-1000"},{"label":"5L","sku":"GL-CON-5000"}]'::jsonb),
  ('דבק מגע בתרסיס', 'GL-CON-SPR', 'דבקים', 'דבק מגע ואפוקסי', 'תרסיס דבק מגע 500 מ"ל לכיסוי מהיר ואחיד של שטחים גדולים. ריסוס מתכוונן רחב/מדויק.', 56, true, 'מבצע', false, '[]'::jsonb),
  ('אפוקסי מהיר 5 דקות', 'GL-EPX-5', 'דבקים', 'דבק מגע ואפוקסי', 'אפוקסי דו-רכיבי במזרק כפול 25 מ"ל עם ערבוב אוטומטי. שקוף, מתקשה תוך 5 דקות לתיקונים.', 34, true, null, false, '[]'::jsonb),
  ('אפוקסי שקוף ליציקה', 'GL-EPX-CAST', 'דבקים', 'דבק מגע ואפוקסי', 'שרף יציקה שקוף בבועות-מינימום לשולחנות נהר ומילוי סיקוסים. יחס ערבוב 2:1, עובי שכבה עד 5 ס"מ.', 220, true, null, false, '[{"label":"750mL","sku":"GL-EPX-CAST-750"},{"label":"1.5L","sku":"GL-EPX-CAST-1500"},{"label":"6L","sku":"GL-EPX-CAST-6000"}]'::jsonb),
  ('ערכת דבק CA + מאיץ', 'GL-CA-KIT', 'דבקים', 'דבק מגע ואפוקסי', 'דבק ציאנואקרילט בצמיגות בינונית 50 גרם עם תרסיס מאיץ. קיבוע נקודתי מיידי בעבודות עץ.', 52, true, null, false, '[]'::jsonb),
  ('דבק פוליאוריתן D4', 'GL-PU-D4', 'דבקים', 'דבק מגע ואפוקסי', 'דבק PU חד-רכיבי תופח ועמיד מים מלא — חיבורי חוץ, עץ קשה ואבן. 500 גרם.', 58, true, null, false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- דבקים › איטום וסיליקון
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('סיליקון ניטרלי', 'GL-SIL-NEU', 'דבקים', 'איטום וסיליקון', 'סיליקון ניטרלי אנטי-פטריות לחדרים רטובים ומטבחים. שומר גמישות לאורך שנים, 280 מ"ל.', 24, true, null, true, '[{"label":"שקוף","sku":"GL-SIL-NEU-CLR"},{"label":"לבן","sku":"GL-SIL-NEU-WHT"},{"label":"אפור","sku":"GL-SIL-NEU-GRY"},{"label":"שחור","sku":"GL-SIL-NEU-BLK"}]'::jsonb),
  ('אקריל לבן ניתן לצביעה', 'GL-ACR-WHT', 'דבקים', 'איטום וסיליקון', 'מסטיק אקרילי למילוי מרווחים וסדקים לפני צבע. עיבוד קל במים, 280 מ"ל.', 14, true, null, false, '[]'::jsonb),
  ('דבק-איטום MS פולימר', 'GL-MS-POLY', 'דבקים', 'איטום וסיליקון', 'MS פולימר היברידי — הדבקה מבנית ואיטום בו-זמנית, ללא ריח וללא התכווצות. 290 מ"ל.', 42, true, 'מבצע', false, '[{"label":"לבן","sku":"GL-MS-POLY-WHT"},{"label":"שחור","sku":"GL-MS-POLY-BLK"}]'::jsonb),
  ('פוליאוריתן PU-40', 'GL-PU40', 'דבקים', 'איטום וסיליקון', 'מסטיק פוליאוריתן אלסטי לתפרי התפשטות ועיגון רעידות. ניתן לצביעה, 300 מ"ל.', 36, true, 'חדש', false, '[]'::jsonb),
  ('סרט הדבקה דו-צדדי VHB', 'GL-TAPE-VHB', 'דבקים', 'איטום וסיליקון', 'סרט אקרילי דו-צדדי בחוזק מבני להדבקת פנלים ומראות ללא ברגים. גליל 19 מ"מ / 11 מטר.', 65, true, 'חדש', false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- גימור › שמנים ולכות
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('שמן Osmo Hardwax', 'FN-OSMO-750', 'גימור', 'שמנים ולכות', 'שמן-ווקס קשיח למשטחי עץ — מגע טבעי, עמידות כתמים ונוזלים. כיסוי כ-12 מ"ר לליטר בשתי שכבות.', 189, true, null, true, '[{"label":"375mL","sku":"FN-OSMO-375"},{"label":"750mL","sku":"FN-OSMO-750"},{"label":"2.5L","sku":"FN-OSMO-2500"}]'::jsonb),
  ('לכה פוליאוריתנית על בסיס מים', 'FN-PU-WB', 'גימור', 'שמנים ולכות', 'לכה חד-רכיבית שקופה בייבוש מהיר וללא הצהבה. עמידות שחיקה גבוהה לרהיטים ומדרגות.', 96, true, null, false, '[{"label":"משי 750mL","sku":"FN-PU-WB-SAT"},{"label":"מבריק 750mL","sku":"FN-PU-WB-GLS"},{"label":"מט 750mL","sku":"FN-PU-WB-MAT"}]'::jsonb),
  ('שמן דני', 'FN-DAN-OIL', 'גימור', 'שמנים ולכות', 'תערובת שמנים חודרת המדגישה את גוון העץ ומספקת הגנה בסיסית. מריחה בבד, קל לחידוש.', 64, true, null, true, '[{"label":"500mL","sku":"FN-DAN-OIL-500"},{"label":"1L","sku":"FN-DAN-OIL-1000"}]'::jsonb),
  ('ווקס משחה לעץ', 'FN-WAX-PST', 'גימור', 'שמנים ולכות', 'ווקס דבורים וקרנובה לליטוש סופי וברק עדין. 400 גרם, מתאים מעל שמן או בייץ.', 48, true, null, false, '[]'::jsonb),
  ('שלאק פתיתים', 'FN-SHELLAC', 'גימור', 'שמנים ולכות', 'פתיתי שלאק דה-ווקס בגוון ענברי להכנה באלכוהול. לגימור מסורתי ושכבת חסימה אוניברסלית. 250 גרם.', 85, true, null, false, '[]'::jsonb),
  ('לכה דו-רכיבית 2K', 'FN-LACQ-2K', 'גימור', 'שמנים ולכות', 'לכה פוליאוריתנית דו-רכיבית להתזה — קשיחות תעשייתית לחזיתות מטבח. ערכה 1 ליטר + מקשה.', 175, true, 'מבצע', false, '[]'::jsonb),
  ('פריימר איטום לעץ', 'FN-PRIMER', 'גימור', 'שמנים ולכות', 'יסוד מים סוגר-סיבים לפני צבע או לכה, נשייף לחלק תוך שעה. 750 מ"ל.', 72, true, null, false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- גימור › שיוף וליטוש
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('נייר לטש (10 יח'')', 'FN-SAND-120', 'גימור', 'שיוף וליטוש', 'גיליונות נייר לטש אלומיניום-אוקסיד 230/280 מ"מ לעבודת יד. אריזת 10 יחידות בגריט אחיד.', 24, true, 'חדש', false, '[{"label":"P80","sku":"FN-SAND-80"},{"label":"P120","sku":"FN-SAND-120"},{"label":"P180","sku":"FN-SAND-180"},{"label":"P240","sku":"FN-SAND-240"}]'::jsonb),
  ('דיסקיות שיוף 125mm (25 יח'')', 'FN-DISC-125', 'גימור', 'שיוף וליטוש', 'דיסקיות סקוץ'' 8 חורים למלטשת אקסצנטרית. ציפוי סטיארט נגד סתימה, אריזת 25.', 42, true, null, false, '[{"label":"P80","sku":"FN-DISC-125-80"},{"label":"P120","sku":"FN-DISC-125-120"},{"label":"P180","sku":"FN-DISC-125-180"},{"label":"P320","sku":"FN-DISC-125-320"}]'::jsonb),
  ('ספוג שיוף גמיש', 'FN-SPONGE', 'גימור', 'שיוף וליטוש', 'ספוג שיוף דו-צדדי לפרופילים ופינות מעוגלות. שטיפה וחוזר לשימוש.', 9, true, null, true, '[{"label":"בינוני","sku":"FN-SPONGE-MED"},{"label":"דק","sku":"FN-SPONGE-FIN"},{"label":"סופר-דק","sku":"FN-SPONGE-SUP"}]'::jsonb),
  ('צמר פלדה 0000', 'FN-WOOL-0000', 'גימור', 'שיוף וליטוש', 'צמר פלדה עדין במיוחד לליטוש בין שכבות ולהברקת ווקס. גליל 200 גרם.', 22, true, null, false, '[]'::jsonb),
  ('משחת ליטוש לגימור', 'FN-POLISH', 'גימור', 'שיוף וליטוש', 'משחת ליטוש עדינה להסרת פגמי התזה והברקה סופית של לכה. 500 גרם.', 39, true, null, false, '[]'::jsonb),
  ('רשתות שיוף 115mm (10 יח'')', 'FN-MESH-115', 'גימור', 'שיוף וליטוש', 'רשתות שיוף ללא אבק בחיבור סקוץ'' — פינוי שבבים מלא דרך הרשת. P120, אריזת 10.', 35, true, 'חדש', false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- גימור › גוונים ופיגמנטים
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('בייץ מים לעץ', 'FN-STAIN', 'גימור', 'גוונים ופיגמנטים', 'בייץ על בסיס מים בחדירה אחידה ללא פסים. ניתן לדילול ולערבוב גוונים, 500 מ"ל.', 46, true, 'מבצע', false, '[{"label":"אלון מעושן","sku":"FN-STAIN-SMK"},{"label":"אגוז כהה","sku":"FN-STAIN-WAL"},{"label":"דובדבן","sku":"FN-STAIN-CHR"},{"label":"אפור ווש","sku":"FN-STAIN-GRY"}]'::jsonb),
  ('פיגמנט לאפוקסי', 'FN-PIG-EPX', 'גימור', 'גוונים ופיגמנטים', 'פיגמנט מרוכז לשרפי אפוקסי — די בכמה טיפות לליטר. גוונים אחידים או אפקט מטאלי, 50 מ"ל.', 28, true, null, false, '[{"label":"שחור פחם","sku":"FN-PIG-EPX-BLK"},{"label":"לבן","sku":"FN-PIG-EPX-WHT"},{"label":"טורקיז","sku":"FN-PIG-EPX-TRQ"},{"label":"נחושת מטאלי","sku":"FN-PIG-EPX-CPR"}]'::jsonb),
  ('צבע אקרילי בגוון RAL', 'FN-TINT-RAL', 'גימור', 'גוונים ופיגמנטים', 'צבע אקרילי משי לעץ ו-MDF בגוון RAL מדויק, כיסוי גבוה. 750 מ"ל, ניתן להתזה ולגלילה.', 88, true, null, false, '[{"label":"RAL 9010 לבן","sku":"FN-TINT-RAL-9010"},{"label":"RAL 7016 אנתרציט","sku":"FN-TINT-RAL-7016"},{"label":"RAL 6034 פסטל","sku":"FN-TINT-RAL-6034"}]'::jsonb),
  ('ערכת הזהבה', 'FN-GILD-KIT', 'גימור', 'גוונים ופיגמנטים', 'ערכת עלי זהב מלאכותיים, מדיום הדבקה ולכת הגנה — להדגשות ושיקום מסגרות. 25 עלים.', 130, true, 'חדש', true, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- כלי עבודה › כלי חשמל
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('מברגה/מקדחה 18V', 'TL-DRILL-18V', 'כלי עבודה', 'כלי חשמל', 'מברגה-מקדחה נטענת 18V עם שתי סוללות 2.0Ah, מטען ומזוודה. מומנט 60Nm, פטרון 13 מ"מ.', 690, true, null, true, '[]'::jsonb),
  ('מסור צלילה + מסילה 1.4מ''', 'TL-TRACK-SAW', 'כלי עבודה', 'כלי חשמל', 'מסור צלילה 165 מ"מ עם מסילת אלומיניום — חיתוכים ישרים ברמת מקצועה בפלטות. כולל להב 48 שיניים.', 1850, true, null, false, '[]'::jsonb),
  ('מלטשת אקסצנטרית 125mm', 'TL-SANDER-125', 'כלי עבודה', 'כלי חשמל', 'מלטשת מסלולית אקראית עם שאיבת אבק ובקרת מהירות. תנופה 2.5 מ"מ לגימור עדין.', 520, true, null, false, '[]'::jsonb),
  ('פרזר (נתב עליון) 1400W', 'TL-ROUTER', 'כלי עבודה', 'כלי חשמל', 'נתב עליון עם צלילה מתכווננת ובקרת סל"ד, קולטים 6/8 מ"מ. כולל מקביל וגביע שאיבה.', 980, true, 'מבצע', false, '[]'::jsonb),
  ('מסור גרונג 255mm', 'TL-MITER-255', 'כלי עבודה', 'כלי חשמל', 'מסור גרונג קומפאונד עם משיכה, זוויות 45/45 וליזר סימון. שולחן יציקה מדויק.', 1390, true, 'מבצע', false, '[]'::jsonb),
  ('שואב אבק נייד Class M', 'TL-VAC-M', 'כלי עבודה', 'כלי חשמל', 'שואב סדנה 1200W עם ניקוי פילטר אוטומטי ושקע הפעלת כלי. תקן אבק M, מיכל 25 ליטר.', 1150, true, null, false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- כלי עבודה › כלי יד
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('סט מברגים 12 יח''', 'TL-SCRW-12', 'כלי עבודה', 'כלי יד', 'סט מברגים מקצועי שטוח/פיליפס/טורקס עם ידיות תלת-רכיב ופלדת S2. כולל מתלה קיר.', 145, true, null, true, '[]'::jsonb),
  ('פטיש נגרים 450 גרם', 'TL-HAMR-450', 'כלי עבודה', 'כלי יד', 'פטיש עם ראש מחושל וידית פיברגלס בולמת זעזועים. מחלץ מסמרים מעוקל.', 89, true, null, false, '[]'::jsonb),
  ('סט איזמלים 4 יח''', 'TL-CHIS-SET', 'כלי עבודה', 'כלי יד', 'איזמלי נגרות 6/12/19/25 מ"מ מפלדת כרום-ונדיום מושחזת, ידיות אשור עם טבעת הקשה.', 220, true, 'חדש', false, '[]'::jsonb),
  ('מקצועה יד מס'' 4', 'TL-PLANE-4', 'כלי עבודה', 'כלי יד', 'מקצועת החלקה קלאסית עם סוליה מושטחת ולהב מתכוונן במיקרומטר. לגימור משטחים בעץ מלא.', 310, true, null, false, '[]'::jsonb),
  ('מלחצי F מהיר', 'TL-CLAMP-F', 'כלי עבודה', 'כלי יד', 'מלחץ F עם ידית מהירה ולסתות מגן. פרופיל פלדה מחוזק, כוח הידוק 120 ק"ג.', 38, true, null, false, '[{"label":"150mm","sku":"TL-CLAMP-F-150"},{"label":"300mm","sku":"TL-CLAMP-F-300"},{"label":"600mm","sku":"TL-CLAMP-F-600"}]'::jsonb),
  ('מסור יפני Ryoba', 'TL-SAW-JPN', 'כלי עבודה', 'כלי יד', 'מסור משיכה דו-צדדי — שיניים לחיתוך לאורך ולרוחב הסיב. להב 240 מ"מ מתחלף.', 165, true, null, false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- כלי עבודה › מקדחים וביטים
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('סט מקדחי פורסטנר', 'TL-FOR-SET', 'כלי עבודה', 'מקדחים וביטים', 'סט 5 מקדחי פורסטנר 15–35 מ"מ לקידוח כוסות צירים ושקעים שטוחי-תחתית. במארז עץ.', 119, true, 'מבצע', false, '[]'::jsonb),
  ('סט מקדחי עץ Brad-Point', 'TL-BRAD-SET', 'כלי עבודה', 'מקדחים וביטים', 'סט 8 מקדחים 3–10 מ"מ עם חוד מרכוז למניעת בריחה. קידוח נקי ללא קרעים.', 68, true, null, true, '[]'::jsonb),
  ('סט כוסות ניסור', 'TL-HOLE-SET', 'כלי עבודה', 'מקדחים וביטים', 'סט 9 כוסות 19–64 מ"מ עם מקדח מוביל ומתאם. לעץ, גבס ופלסטיק.', 95, true, null, false, '[]'::jsonb),
  ('סט ביטים טורקס 32 יח''', 'TL-BITS-TRX', 'כלי עבודה', 'מקדחים וביטים', 'ביטים מצופי טיטניום עם אזור פיתול בולם — אריכות חיים כפולה. כולל מחזיק מגנטי.', 54, true, 'מבצע', false, '[]'::jsonb),
  ('שוקע + מקדח מוביל', 'TL-CSINK', 'כלי עבודה', 'מקדחים וביטים', 'מקדח משולב עם שוקע מתכוונן וטבעת עצירה — קדח, שקע ועומק בפעולה אחת.', 32, true, null, false, '[{"label":"3mm","sku":"TL-CSINK-3"},{"label":"4mm","sku":"TL-CSINK-4"},{"label":"5mm","sku":"TL-CSINK-5"}]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- כלי עבודה › מדידה וסימון
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('מטר 5 מטר מגנטי', 'TL-TAPE-5M', 'כלי עבודה', 'מדידה וסימון', 'סרט מדידה 5 מ'' עם וו מגנטי, נעילה כפולה וציפוי ניילון. דיוק Class II.', 36, true, 'חדש', false, '[]'::jsonb),
  ('זווית משולבת 300mm', 'TL-SQR-COMB', 'כלי עבודה', 'מדידה וסימון', 'זווית קומבינציה עם סרגל נירוסטה חרוט, ראש 90°/45° ופלס מובנה. לסימון וכיוון מכונות.', 98, true, null, false, '[]'::jsonb),
  ('קליבר דיגיטלי 150mm', 'TL-CALIPER', 'כלי עבודה', 'מדידה וסימון', 'קליבר דיגיטלי נירוסטה ברזולוציית 0.01 מ"מ, מדידת פנים/חוץ/עומק. כולל סוללה וקופסה.', 120, true, null, false, '[]'::jsonb),
  ('פלס אלומיניום 60 ס"מ', 'TL-LEVEL-60', 'כלי עבודה', 'מדידה וסימון', 'פלס פרופיל מחוזק עם 3 בועות ומשטחי מדידה כפולים. דיוק 0.5 מ"מ/מ''.', 75, true, 'מבצע', true, '[]'::jsonb),
  ('ערכת סימון נגרים', 'TL-MARK-KIT', 'כלי עבודה', 'מדידה וסימון', 'עפרון נגרים מכני 2.8 מ"מ, סכין סימון וגרד מקבילי (Marking Gauge) בערכה אחת.', 58, true, 'חדש', false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- תאורה › פסי LED וספקים
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('פס LED 24V (5 מטר)', 'LT-LED-24-5', 'תאורה', 'פסי LED וספקים', 'פס לדים 24V צפיפות 120 לד/מטר עם דבק 3M מקורי. CRI>90, ניתן לחיתוך כל 5 ס"מ.', 79, true, null, true, '[{"label":"3000K","sku":"LT-LED-24-30"},{"label":"4000K","sku":"LT-LED-24-40"},{"label":"6000K","sku":"LT-LED-24-60"}]'::jsonb),
  ('פס COB רציף (5 מטר)', 'LT-LED-COB', 'תאורה', 'פסי LED וספקים', 'פס COB ללא נקודות אור נראות — קו אור אחיד לחלוטין. 24V, 512 לד/מטר.', 145, true, null, false, '[{"label":"3000K","sku":"LT-LED-COB-30"},{"label":"4000K","sku":"LT-LED-COB-40"},{"label":"6000K","sku":"LT-LED-COB-60"}]'::jsonb),
  ('ספק כוח 24V', 'LT-PSU', 'תאורה', 'פסי LED וספקים', 'ספק מיתוג 24V שקט בעל הגנות עומס-יתר וקצר. מארז מתכת עם פס חיבורים.', 88, true, null, false, '[{"label":"60W","sku":"LT-PSU-60"},{"label":"100W","sku":"LT-PSU-100"},{"label":"150W","sku":"LT-PSU-150"}]'::jsonb),
  ('פרופיל אלומיניום לפס LED', 'LT-PROF-ALU', 'תאורה', 'פסי LED וספקים', 'פרופיל אלומיניום 2 מטר עם מפזר אופל וסגירות קצה. פיזור חום מאריך חיי לד.', 42, true, null, false, '[{"label":"שקוע 2מ''","sku":"LT-PROF-ALU-REC"},{"label":"צמוד 2מ''","sku":"LT-PROF-ALU-SRF"},{"label":"פינתי 2מ''","sku":"LT-PROF-ALU-CRN"}]'::jsonb),
  ('בקר דימור RF + שלט', 'LT-DIM-RF', 'תאורה', 'פסי LED וספקים', 'בקר עמעום אלחוטי לפסי LED עד 8A עם שלט מגע 4 אזורים. זיכרון מצב אחרון.', 96, true, 'חדש', false, '[]'::jsonb),
  ('מגבר אות 24V', 'LT-AMP-24', 'תאורה', 'פסי LED וספקים', 'מגבר RGB/CCT להארכת פסים מעבר ל-5 מטר ללא נפילת בהירות. חיבורי בורג.', 38, true, null, true, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- תאורה › גופי תאורה
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('ספוט שקוע LED 7W', 'LT-SPOT-7', 'תאורה', 'גופי תאורה', 'ספוט שקוע 7W בקוטר חיתוך 75 מ"מ, דרייבר מובנה. זווית 38°, אלומיניום צבוע לבן.', 29, true, 'מבצע', false, '[{"label":"3000K","sku":"LT-SPOT-7-30"},{"label":"4000K","sku":"LT-SPOT-7-40"},{"label":"6000K","sku":"LT-SPOT-7-60"}]'::jsonb),
  ('ספוט צמוד מתכוונן', 'LT-SPOT-SRF', 'תאורה', 'גופי תאורה', 'ספוט צילינדר צמוד תקרה עם ראש מסתובב 350°. GU10 מתחלף, עיצוב מינימליסטי.', 64, true, null, false, '[{"label":"שחור","sku":"LT-SPOT-SRF-BLK"},{"label":"לבן","sku":"LT-SPOT-SRF-WHT"}]'::jsonb),
  ('תאורת מגירה עם חיישן', 'LT-DRAW-SENS', 'תאורה', 'גופי תאורה', 'פס תאורה נטען USB עם חיישן פתיחה — נדלק עם פתיחת המגירה. הדבקה מגנטית, 30 ס"מ.', 55, true, 'מבצע', false, '[]'::jsonb),
  ('מוט תלייה מואר לארון', 'LT-WARD-ROD', 'תאורה', 'גופי תאורה', 'מוט קולבים עם תאורת LED מובנית וחיישן תנועה. אלומיניום אובלי, כולל ספק.', 110, true, null, false, '[{"label":"600mm","sku":"LT-WARD-ROD-600"},{"label":"900mm","sku":"LT-WARD-ROD-900"},{"label":"1200mm","sku":"LT-WARD-ROD-1200"}]'::jsonb),
  ('מנורת עבודה מפרקית', 'LT-WORK-LAMP', 'תאורה', 'גופי תאורה', 'מנורת שולחן מפרקית עם תפס שולחן, 12W ושלוש דרגות גוון. זרוע 80 ס"מ.', 180, true, null, false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;

-- תאורה › חיישנים ומתגים
insert into public.products
  (name, sku, category, subcategory, description, base_price, active, badge, featured, variants)
values
  ('חיישן תנועה PIR שקוע', 'LT-PIR-12', 'תאורה', 'חיישנים ומתגים', 'חיישן תנועה זעיר להתקנה שקועה בריהוט, 12–24V עד 3A. טווח 3 מ'', השהיה מתכווננת.', 34, true, null, false, '[]'::jsonb),
  ('חיישן דלת IR', 'LT-DOOR-SW', 'תאורה', 'חיישנים ומתגים', 'מתג קרבה אינפרא-אדום — מדליק תאורת ארון עם פתיחת הדלת. שקוע 12 מ"מ, 24V.', 28, true, null, true, '[]'::jsonb),
  ('מתג מגע דימר שקוע', 'LT-TOUCH-DIM', 'תאורה', 'חיישנים ומתגים', 'מתג מגע עם עמעום רציף בלחיצה ארוכה, להתקנה מאחורי חזית עץ עד 20 מ"מ. 24V/4A.', 45, true, 'חדש', false, '[]'::jsonb),
  ('חיישן נפנוף יד', 'LT-HAND-WAVE', 'תאורה', 'חיישנים ומתגים', 'הפעלת תאורה בנפנוף יד ללא מגע — אידיאלי לסוקל מטבח ומראות. 12-24V, IP44.', 52, true, 'מבצע', false, '[]'::jsonb)
on conflict (sku) where sku is not null and sku <> '' do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  base_price = excluded.base_price,
  badge = excluded.badge,
  featured = excluded.featured,
  variants = excluded.variants;
